#
# Copyright (c) 2021 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
[package]
name = "ros2-teleop"
version = "0.0.1"
repository = "https://github.com/JEnoch/ROS2-playground"
authors = ["Julien Enoch <julien@enoch.fr>"]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "A ROS2 simple teleop app using Eclipse zenoh"
readme = "./README.md"

[dependencies]
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git" }
async-std = { version = "=1.10.0", default-features = false, features = ["attributes",] }
futures = "0.3.12"
serde = "1"
serde_derive = "1"
cdr = "0.2.4"
log = "0.4"
env_logger = "0.9"
clap = {version="3.1" }
crossterm = "0.23"

[[bin]]
name = "ros2-teleop"
